### ISSUE TITLE
Can I create an Outlook rule to create a Calendar Alert from Mail Body

### ISSUE THREAD

**Issue by jatsptl** [tillig/tillig.github.io#1]
What I am trying to do is create an calendar event from mail body as below.

If I receive any mail with message body as Due Date:01/01/2015 it should create a event in calendar and also alert me whenever that date and time occurs.

Is this possible by rule or macro? Any help would be much appreciated.

**Comment by tillig** [comment]
I'm sure you probably could do this, though I've not tried it.

You could try [starting with my code to convert a message to a task](http://www.paraesthesia.com/archive/2007/07/10/convert-an-outlook-message-into-a-task.aspx/) and then combine it with some of the logic from this ["create an Outlook appointment from an email message"](http://www.slipstick.com/developer/code-samples/create-outlook-appointment-from-message/) page.

I don't really have time to write it for you or I'd put some finished code up here.

Hope that helps!
