### ISSUE TITLE
Distributed cache with OpenIdConnect

### ISSUE THREAD

**Issue by Yavor81** [tillig/tillig.github.io#10]
Hi,
I have the following scenario.
My web application is using the OpenIdConnect middleware to authenticate the application through a company Identity Server. My goal is to make a setup for multiple nodes/web farm scenario, where the authenticated session is shared across all node servers. The requirement is to store the distributed cache in a MongoDb database. I can use the MongoDbCache package that implements of IDistributedCache.
How can I achieve this scenario?
I looked into this:
http://www.paraesthesia.com/archive/2016/06/15/set-up-asp-net-dataprotection-in-a-farm/
But I am not sure how can I share the access token to be used by all instances.

**Comment by tillig** [comment]
ASP.NET data protection doesn't have anything to do with the OpenIdConnect stuff in IdentityServer. I'd recommend asking your question on StackOverflow or on the IdentityServer issues list.
