### ISSUE TITLE
Loyalty Card barcode generator moved, causes download to fail

### ISSUE THREAD

**Issue by wga22** [tillig/tillig.github.io#11]
Travis - I cannot seem to get the "download" button to work.  Clicking it does nothing.

Sample:
[http://app-paraesthesia-com.azurewebsites.net/LoyaltyCard/?%5B%5B%22Giant%22%2C%220%22%2C%224400274%22%5D%5D](http://app-paraesthesia-com.azurewebsites.net/LoyaltyCard/?%5B%5B%22Giant%22%2C%220%22%2C%224400274%22%5D%5D)

**Comment by tillig** [comment]
Oh, man, it looks like the barcode generator I was using moved. I'll have to see how to fix that.

**Comment by tillig** [comment]
OK, fixed. You should be able to click your link and your data should still be there. If you don't see a barcode preview just to the right of the text entry boxes, hold down the Shift key and click refresh in your browser to force a reload of the page. Once you see the preview, the download button should work for you.
