### ISSUE TITLE
Autofac Error 

### ISSUE THREAD

**Issue by junwangwj** [tillig/tillig.github.io#12]
I use autofac RegisterInstance,but have error, .NetFramework 4.0 and   have install  (KB2468871).
but  still have error;
I insatll the  (KB2468871) in server 2008 r2   and   without network 
I  need a help 
Thanks very match !

code：
var builder = new ContainerBuilder();
builder.RegisterModule(new MappingModule() { IsMultiThread = MappingRule.IsMultiThread });
builder.RegisterInstance<MappingContext>(MappingContext);

Stack Error：
 at Autofac.Builder.RegistrationData..ctor(Service defaultService)
   at Autofac.Builder.RegistrationBuilder`3..ctor(Service defaultService, TActivatorData activatorData, TRegistrationStyle style)
   at Autofac.RegistrationExtensions.RegisterInstance[T](ContainerBuilder builder, T instance)

error：
Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)

**Comment by tillig** [comment]
Looks like you opened this on the Autofac repo, too. I'll close this duplicate.
