### ISSUE TITLE
No Cat Pictures

### ISSUE THREAD

**Issue by ywapom** [tillig/tillig.github.io#15]
"Paraesthesia: .NET Development and Some Pictures of My Cat"
I like your blog but I found zero cat pictures

**Comment by tillig** [comment]
[Here's the latest.](http://www.paraesthesia.com/archive/2018/01/10/goodnight-princess-xev/) Unfortunately, she's passed and we now just have my wife's [two boys.](http://www.paraesthesia.com/archive/2008/07/06/welcome-kai-and-stanley.aspx/) 😢
