### ISSUE TITLE
Meetup information

### ISSUE THREAD

**Issue by pccmtn** [tillig/tillig.github.io#16]
Good evening Travis,
 
I am a researcher at Erasmus University Rotterdam. I would like to ask someone at Typemock a few questions about the impact of sponsoring meetup.com events.
It will be a very short chat but it would help me immensely to progress!

Do you know someone I could speak to to have some information?
Of course I will share any findings with the company after I have any.
 
Hope to speak soon,
 
Best regards,
 
Martina Pocchiari | PhD Candidate
Rotterdam School of Management | Erasmus University

**Comment by tillig** [comment]
Sorry, I don't work for Typemock. You'll have better luck contacting them directly.
