### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by allofthelines** [tillig/tillig.github.io#17]
Super radom question, i know, but would you mind if asked you a few questions about the current state of your skin after the beard removal you did in the past?

I stumbled upon your post where you depict in great detail what happened, and since i'm contemplating on doing it too i would appreciate the feedback.

Thanks!

**Comment by tillig** [comment]
Check out #7 and [my wrap-up summary post](https://www.paraesthesia.com/archive/2010/05/10/laser-hair-removal-before-and-after.aspx/) to see if they answer your questions. The pictures you see in the wrap up post are how my skin still is, nine years later.
