### ISSUE TITLE
Your House Layout

### ISSUE THREAD

**Issue by Coldrider** [tillig/tillig.github.io#2]
Hi, I was wondering if you could you send me a copy of your home digram setup. I would like to use to show the layout of my setup if you do not mind.

Thank you 

Rob Burns

robeditor2003@yahoo.com

**Comment by tillig** [comment]
Are you asking for the original Visio diagram of my home theater setup? I have it [posted here on Github](https://github.com/tillig/mediacenter/blob/master/docs/network/diagram.vsdx). If that's not what you're looking for, let me know and I'll see if I can help.

**Comment by Coldrider** [comment]
Travis,

Sorry for getting back to you late. Work stuff.. Yes thank you for the file.

On Sat, Jul 18, 2015 at 9:58 PM, Travis Illig notifications@github.com
wrote:

> Closed #2 https://github.com/tillig/tillig.github.io/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tillig/tillig.github.io/issues/2#event-359375094.

## 

Rob Burns
I.T. Digital Media Consultant
@rburnsdirect rburnsdirect@gmail.com
818-217-0584
