### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by kknd4eva** [tillig/tillig.github.io#23]
Hi Travis, 

Just wanted to say thank you for your post @ https://www.paraesthesia.com/archive/2019/06/18/tips-on-container-tools-for-visual-studio/. 

It's been really helpful for me to understand some of the magic that Visual Studio does under the covers around Docker support, as I've been struggling with working between environments (dev, production etc) and how to use configuration and environment variables around these environments with .NET Core and Docker. So thanks!

**Comment by tillig** [comment]
Glad to help!
