### ISSUE TITLE
Question in regards of your Oauth2-proxy blog

### ISSUE THREAD

**Issue by miketoupin** [tillig/tillig.github.io#25]
First of all, your blog is really fantastic. I just want to know if you do have a NGINX ingress in front of your Oauth2-proxy setup?  I did the same setup as you do and I cannot pass on the token to my Grafana app which is configured to permit login with a token.  Maybe this is Grafana config which is wrong but I wanted to ensure your setup does not require NGINX in front of Oauth-Proxy.

Thanks!

**Comment by tillig** [comment]
No, I don't have nginx ingress anywhere in the picture. Istio is the only ingress. Grafana [appears to have OAuth built in](https://grafana.com/docs/grafana/latest/auth/generic-oauth/) so there's no need for oauth2-proxy or anything else in place. Likely my article won't help you at all - you just need a basic ingress that goes straight through to Grafana and let Grafana do its thing.
