### ISSUE TITLE
about 3018cnc upgrade

### ISSUE THREAD

**Issue by yusufkursun96** [tillig/tillig.github.io#28]
Hi! I was wondering how did you mount the new router on the cnc machine?
https://www.paraesthesia.com/archive/2020/08/24/cnc-3018-spindle-power-control-with-relay/
I have 3018 sainsmart router and I want to upgrade it same like your machine!!!

**Comment by tillig** [comment]
As noted in the article:

>First, you have to figure out how to mount the router to the CNC frame. I solved this by creating a 3D printed [combination holder and dust shoe, which you can get on Thingiverse](https://www.thingiverse.com/thing:4570845).

However, you should know (and I should update the article) that the base 3018PRO doesn't have strong enough stepper motors to drive that Makita router I tried. Doing simple 2D work was fine (like cutting letters in a sign) but in 3D work (like a carving) I lost Z height and it ruined the work. If you have the 3018PROVer or one of the slightly upgraded models, it shouldn't be a problem. It's just the very base model doesn't have enough juice.

**Comment by yusufkursun96** [comment]
Uhh I understand now, thank you so much!! I really appreciate it!!!!!!

**Comment by tillig** [comment]
I've updated the article just now so it should hopefully help others. Good luck!

**Comment by yusufkursun96** [comment]
And also i have one more question, after you install the new bigger router,
did you working area reduce cause of the mounting parts...?

**Comment by tillig** [comment]
Nope.
