### ISSUE TITLE
Gotcha: This doesn’t help with assembly binding problems

### ISSUE THREAD

**Issue by morbius1st** [tillig/tillig.github.io#29]
I have read your article "How to Debug the XAML Designer" more than once - I have a project that, out of nowhere, showed multiple errors and the majority of the UI would not display in the WPF / Xaml designer.  This is actually the second time in the same solution.  
I cannot say what the real problem is - I looked at the shadow cache area you indicated and found nothing - I looked at some adjacent folders and did find a cache (maybe the new shadow cache).  
Anyway - long story short, I did something that, so far, seems to have gotten around the problem.  I changed the ProjectGuid in both the solution file and the project file - just changed the first number.  It looks like this caused VS to generate a new cache and cache identifiers and, whatever was causing the problem, stayed with the old cache / cache id.  The project displays correctly in the designer now (for the other project too).
I hope that this helps you if you ever need this in the future (or the past).

**Comment by tillig** [comment]
Thanks! If I ever hit this again, I'll look into it.
