### ISSUE TITLE
A new VS Code extension inspired by you.

### ISSUE THREAD

**Issue by goohan** [tillig/tillig.github.io#30]
Hello, I want to tell you that I have created [this extension](https://marketplace.visualstudio.com/items?itemName=goohan.plantumlautogenerator) inspired by your article: [PlantUML Diagrams in Azure DevOps Wiki Pages ](https://www.paraesthesia.com/archive/2020/05/11/plantuml-in-azure-devops-wiki/). Thank you very much.

**Comment by tillig** [comment]
Wow, that's awesome! Nice work!
