### ISSUE TITLE
File Upload checking MultipartFormData

### ISSUE THREAD

**Issue by gnutwist** [tillig/tillig.github.io#31]
Hi Travis,

I found your 2009 vb post pertaining to multipartFormData on paraesthesia today 4/27/2023... and had a few questions on how to implement it to check Content-Disposition against Content-Type as a way of validating file types being uploaded to a website.

I clicked on your Contact link, and it brought me here. Could you help me understand how this would need to be set up please?

Thanks in advance,
Randy

**Comment by tillig** [comment]
While I love that you found something here that might help get you started, I am unfortunately swamped by my day job at the moment, pushing that 60 hour week and trying to maintain a bit of the ol' work/life balance. That means I'm not really able to offer direct support or free contracting hours to help you get these things set up. I do apologize that I can't dig in and help; I really do want to help folks, but there just isn't enough time. I wish there was.
