### ISSUE TITLE
Generate Strongly-Typed Resources with .NET Core - a thankyou!

### ISSUE THREAD

**Issue by andymantell** [tillig/tillig.github.io#32]
Hi Travis, 

Just wanted to pass on my thanks for your "[Generate Strongly-Typed Resources with .NET Core](https://www.paraesthesia.com/archive/2022/09/30/strongly-typed-resources-with-net-core/)" blog post. Just got this going on the project I'm working on thanks to your writeup. Was pretty stumped until then!

Cheers! 🍺 

Andy

**Comment by tillig** [comment]
Glad to help! If you want to make it even easier, one of the Autofac maintainers showed me how to [make an item definition](https://github.com/autofac/Autofac/blob/d2ed00a046c2d47374ee7a1517fabf2c4eb80c81/src/Autofac/Autofac.csproj#L88) to remove a lot of the boilerplate. I should probably update the blog article with that at some point. 

Take it easy!

**Comment by andymantell** [comment]
Ah that's very cool. Thankfully I think I'll only have two resource files for the forseeable future so I won't need that, but thanks for the heads up!
