### ISSUE TITLE
Random Question

### ISSUE THREAD

**Issue by weishuhn** [tillig/tillig.github.io#4]
Did you ever find an answer to how to [add TransformOnBuild](http://www.paraesthesia.com/archive/2013/05/15/setting-dependentupon-file-properties-on-nuget-package-install.aspx/) to the items in the csproj file?  A friend and I were banging our heads against this for a long time today and I just came across your post.  

Thanks!

Mike

**Comment by tillig** [comment]
Unfortunately, I didn't figure it out. I banged my head on the stuff in that article for quite some time and got it far enough that fighting that last bit was diminishing returns. Sorry.

**Comment by weishuhn** [comment]
Damn.  We were getting to the same place.  Thanks.
