### ISSUE TITLE
Request for Autofac 3.5.2 code

### ISSUE THREAD

**Issue by futsystems** [tillig/tillig.github.io#8]
hello
       i am using autofac in my project, it work good. i upgrade Common.Logging component these days,but i have no source code of autofac 3.5.2. i find in google. but still can not get it.
      can you send me source code of autofac 3.5.2, i am using autofac.dll and Autofac.Configuration.dll.
thanks

**Comment by tillig** [comment]
Autofac [moved to GitHub](https://github.com/autofac) some years back. We [tagged at version 3.5.2](https://github.com/autofac/Autofac/tree/v3.5.2) just before splitting individual packages into their own repos. You can get the code you want [from that tag](https://github.com/autofac/Autofac/tree/v3.5.2).
