### ISSUE TITLE
ASP.NET Core Web Farm Setup

### ISSUE THREAD

**Issue by dannyhchan** [tillig/tillig.github.io#9]
Hi,
I came across your article (http://www.paraesthesia.com/archive/2016/06/15/set-up-asp-net-dataprotection-in-a-farm/).  You mentioned about using Data Protection in a web farm.  I was wondering if using DataProtection is required to setup a web farm using ASP.NET Core.

Currently, I'm playing around with Core and want to try setting up in a web farm environment.  I have already setup SQL Session using distributed cache.  Using this simple setup, does Core automatically setup as a web farm after deployment.  In old ASP.NET Framework, a machine key is used, but I have no idea how Core works to setup the web farm.

Any guidance would be appreciated.

Thank you.
Dan

**Comment by tillig** [comment]
You do need to set up DataProtection for a farm if you are using any sort of encryption or validation (view state encryption, shared session state, HMAC validation, stuff like that). It's the replacement for machine key in .NET Core - you don't have web.config or machine key anymore. This does not happen automatically, which is the whole point of the article - it's not automatic, and it's not immediately intuitive that it's not happening for you automatically, especially if you've been playing with Azure where they have special magic code that makes it _seem_ automatic.

There are links in my blog article to the documentation about this stuff. Click the links and read the docs. It's not something I can summarize in an issue thread here any better than I did in my article.

**Comment by dannyhchan** [comment]
Sounds good.  Thank you!
